name: udacity
channels:
  - conda-forge
  - defaults
dependencies:
  - nltk=3.4.4
  - numpy=1.15.2
  - pandas=0.23.3
  - python=3.6.3
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - sqlalchemy=1.3.13
  - sqlite=3.20.1

